#!/bin/zsh

case $1 in
  git@*)
    domain=`echo ${1} | sed 's/git@//' | awk '{ sub(":.*$",""); print $0; }'`
    user=`echo ${1} | awk -F ':' '{print $2}' | awk -F '/' '{print $1}'`
    clone_path="${HOME}/git/${domain}/${user}/"
    bash -c "mkdir -p ${clone_path}"
    bash -c "cd ${clone_path}; git clone ${1}"
    ;;
  https://*)
    domain=`echo ${1} | sed 's/https:\/\///' | awk '{ sub("/.*$",""); print $0; }'`
    user=`echo ${1} | awk -F 'github.com/' '{print $2}' | awk -F '/' '{print $1}'`
    clone_path="${HOME}/git/${domain}/${user}/"
    bash -c "mkdir -p ${clone_path}"
    bash -c "cd ${clone_path}; git clone ${1}"
    ;;
  github.com/*)
    domain="github.com"
    user=`echo ${1} | awk -F 'github.com/' '{print $2}' | awk -F '/' '{print $1}'`
    repo=`echo ${1} | awk -F 'github.com/' '{print $2}' | awk -F '/' '{print $2}'`
    clone_path="${HOME}/git/${domain}/${user}/"
    bash -c "mkdir -p ${clone_path}"
    bash -c "cd ${clone_path}; git clone git@${domain}:${user}/${repo}.git"
    ;;
  bitbucket.org/*)
    domain="bitbucket.org"
    user=`echo ${1} | awk -F 'bitbucket.org/' '{print $2}' | awk -F '/' '{print $1}'`
    repo=`echo ${1} | awk -F 'bitbucket.org/' '{print $2}' | awk -F '/' '{print $2}'`
    clone_path="${HOME}/git/${domain}/${user}/"
    bash -c "mkdir -p ${clone_path}"
    bash -c "cd ${clone_path}; git clone git@${domain}:${user}/${repo}.git"
    ;;
esac
