
export SHELL="/usr/bin/zsh"

# curl用
setopt nonomatch

# 履歴
HISTFILE=~/.zsh_history
HISTSIZE=10000
SAVEHIST=10000
setopt hist_ignore_dups
setopt hist_ignore_all_dups
setopt share_history

# 補完
autoload -Uz compinit
compinit -u
if [ -e /usr/local/share/zsh-completions ]; then
  fpath=(/usr/local/share/zsh-completions $fpath)
fi
zstyle ':completion:*' matcher-list 'm:{a-z}={A-Z}'
setopt list_packed
zstyle ':completion:*' list-colors ''

# スペル
setopt correct

# ビープ音
setopt no_beep

# エイリアス
case ${OSTYPE} in
  darwin*)
  alias ls='ls -G'
    ;;
  linux*)
  alias ls='ls --color'
    ;;
esac
alias ll='ls -l'
alias vim='nvim'
alias pbcopy='xsel -bi'

export CLICOLOR=1
export LSCOLORS=DxGxcxdxCxegedabagacad

# tmux
if [[ ! -n $TMUX ]]; then
  # get the IDs
  ID="`tmux list-sessions`"
  if [[ -z "$ID" ]]; then
    tmux new-session && exit
  fi
  create_new_session="Create New Session"
  ID="$ID\n${create_new_session}:"
  ID="`echo $ID | $PERCOL | cut -d: -f1`"
  if [[ "$ID" = "${create_new_session}" ]]; then
    tmux new-session && exit
  fi
  tmux attach-session -t "$ID"
fi

# mac only
if [[ -e $HOME/.nodebrew ]]; then
  nodebrew use 8.9.0 > /dev/null
  export PATH=$PATH:$HOME/.nodebrew/current/bin
fi

# golang
export GOPATH=$HOME/go
export GOROOT=$( go env GOROOT )
export PATH=$PATH:$GOPATH/bin

# nimlang
export PATH=$PATH:~/.nimble/bin

# ros
if [[ -e /opt/ros ]]; then
  source /opt/ros/kinetic/setup.zsh
fi

# git
alias delete-merged-branch="git branch --merged | grep -v '*' | xargs -I % git branch -d %"

export NVM_DIR="/home/hiro/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"  # This loads nvm
