# vcs_infoロード
autoload -Uz vcs_info    

# PROMPT変数内で変数参照する
setopt prompt_subst

# vcsの表示
zstyle ':vcs_info:*' formats '(%F{green}%b%f)'

# プロンプト表示直前にvcs_info呼び出し
precmd() { vcs_info }

# プロンプト表示
export PROMPT='${vcs_info_msg_0_}%# '
export SHELL="/usr/bin/zsh"
export TERM="screen-256color"

# 自作スクリプトのパス
export PATH=$PATH:~/.cui-conf-bin

# curl用
setopt nonomatch

# 履歴
HISTFILE=~/.zsh_history
HISTSIZE=10000
SAVEHIST=10000
setopt hist_ignore_dups
setopt hist_ignore_all_dups
setopt share_history

# 補完
autoload -Uz compinit
compinit -u
if [ -e /usr/local/share/zsh-completions ]; then
  fpath=(/usr/local/share/zsh-completions $fpath)
fi

# color
export LSCOLORS=gxfxcxdxbxegedabagacag
export LS_COLORS='di=36;40:ln=35;40:so=32;40:pi=33;40:ex=22;40:bd=34;46:cd=34;43:su=30;41:sg=30;46:tw=30;42:ow=30;46'
zstyle ':completion:*:default' list-colors ${(s.:.)LS_COLORS}
zstyle ':completion:*' matcher-list 'm:{a-z}={A-Z}'
setopt list_packed

# スペル
setopt correct

# ビープ音
setopt no_beep

# エイリアス
case ${OSTYPE} in
  linux*)
  alias ls='ls --color -lhGF'
    ;;
esac
alias ll='ls -l'
alias vim='nvim'
alias pbcopy='xsel -bi'

export CLICOLOR=1
export LSCOLORS=DxGxcxdxCxegedabagacad

# tmux
if [[ ! -n $TMUX ]]; then
  # get the IDs
  ID="`tmux list-sessions`"
  if [[ -z "$ID" ]]; then
    tmux new-session && exit
  fi
  create_new_session="Create New Session"
  ID="$ID\n${create_new_session}:"
  ID="`echo $ID | $PERCOL | cut -d: -f1`"
  if [[ "$ID" = "${create_new_session}" ]]; then
    tmux new-session && exit
  fi
  tmux attach-session -t "$ID"
fi

# mac only
if [[ -e $HOME/.nodebrew ]]; then
  nodebrew use 8.9.0 > /dev/null
  export PATH=$PATH:$HOME/.nodebrew/current/bin
fi

# golang
export GOPATH=$HOME/go
export GOROOT=$( go env GOROOT )
export PATH=$PATH:$GOPATH/bin

# nimlang
export PATH=$PATH:~/.nimble/bin:/sbin:/usr/sbin

# ros
if [[ -e /opt/ros ]]; then
  source /opt/ros/kinetic/setup.zsh
fi

# git
alias delete-merged-branch="git branch --merged | grep -v '*' | xargs -I % git branch -d %"

export NVM_DIR="/home/hiro/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"  # This loads nvm

cd $HOME

